FROM busybox:1.36

COPY --chmod=0755 sysbox-runc/build/amd64/sysbox-runc /sysbox-bin/sysbox-runc
COPY --chmod=0755 sysbox-snapshotter/build/amd64/sysbox-snapshotter /sysbox-bin/sysbox-snapshotter
COPY --chmod=0755 sysbox-admission/build/amd64/sysbox-admission /sysbox-bin/sysbox-admission

CMD ["sleep", "infinity"]
