package admission

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"strings"

	corev1 "k8s.io/api/core/v1"
)

const (
	AnnotationRootfsRwLayer = "sysbox/rootfs-rw-layer"
	AnnotationVolumeInit    = "sysbox/volume-init"
)

type Config struct {
	SandboxImage string
}

type Mutator struct {
	sandboxImage string
}

type RootfsRwLayerEntry struct {
	Name                    string   `json:"name"`
	VolumeName              string   `json:"volumeName"`
	Path                    string   `json:"path"`
	PersistentSpecialMounts bool     `json:"persistentSpecialMounts,omitempty"`
	SpecialPath             []string `json:"specialPath,omitempty"`
}

// VolumeInitEntry is generated by the admission webhook from trusted Pod PVC
// declarations. It is consumed by sysbox-runc; users don't configure it.
type VolumeInitEntry struct {
	Name       string `json:"name"`
	VolumeName string `json:"volumeName"`
	MountPath  string `json:"mountPath"`
}

func NewMutator(config Config) *Mutator {
	return &Mutator{sandboxImage: config.SandboxImage}
}

func (m *Mutator) Mutate(ctx context.Context, pod *corev1.Pod) (*corev1.Pod, error) {
	mutated := pod.DeepCopy()
	_, enabled, err := m.mutatePod(ctx, mutated)
	if err != nil || !enabled {
		return mutated, err
	}
	return mutated, nil
}

func (m *Mutator) mutatePod(ctx context.Context, pod *corev1.Pod) ([]RootfsRwLayerEntry, bool, error) {
	spec := &pod.Spec
	if spec.RuntimeClassName == nil || *spec.RuntimeClassName != "sysbox-runc" {
		return nil, false, nil
	}
	if err := setVolumeInitAnnotation(pod); err != nil {
		return nil, false, err
	}
	entries, enabled, err := parseRootfsAnnotation(pod.Annotations, spec)
	if err != nil {
		return nil, false, err
	}
	if err := ctx.Err(); err != nil {
		return nil, false, err
	}
	if enabled {
		if err := ensureSidecar(spec, entries, m.sandboxImage); err != nil {
			return nil, false, err
		}
	}
	return entries, true, nil
}

func setVolumeInitAnnotation(pod *corev1.Pod) error {
	entries := collectVolumeInitEntries(&pod.Spec)
	if len(entries) == 0 {
		if pod.Annotations != nil {
			delete(pod.Annotations, AnnotationVolumeInit)
		}
		return nil
	}
	if pod.Annotations == nil {
		pod.Annotations = map[string]string{}
	}
	raw, err := json.Marshal(entries)
	if err != nil {
		return fmt.Errorf("marshal %s annotation: %w", AnnotationVolumeInit, err)
	}
	pod.Annotations[AnnotationVolumeInit] = string(raw)
	return nil
}

func collectVolumeInitEntries(spec *corev1.PodSpec) []VolumeInitEntry {
	pvcs := make(map[string]struct{})
	for _, volume := range spec.Volumes {
		if volume.PersistentVolumeClaim != nil {
			pvcs[volume.Name] = struct{}{}
		}
	}
	entries := make([]VolumeInitEntry, 0)
	appendContainer := func(container corev1.Container) {
		if container.Name == SidecarContainerName {
			return
		}
		for _, mount := range container.VolumeMounts {
			if mount.ReadOnly {
				continue
			}
			if _, ok := pvcs[mount.Name]; !ok {
				continue
			}
			entries = append(entries, VolumeInitEntry{
				Name:       container.Name,
				VolumeName: mount.Name,
				MountPath:  filepath.Clean(mount.MountPath),
			})
		}
	}
	for _, container := range spec.Containers {
		appendContainer(container)
	}
	return entries
}

func parseRootfsAnnotation(annotations map[string]string, spec *corev1.PodSpec) ([]RootfsRwLayerEntry, bool, error) {
	raw := annotations[AnnotationRootfsRwLayer]
	if raw == "" {
		return nil, false, nil
	}
	var entries []RootfsRwLayerEntry
	decoder := json.NewDecoder(strings.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&entries); err != nil {
		return nil, false, fmt.Errorf("invalid %s annotation: %w", AnnotationRootfsRwLayer, err)
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return nil, false, fmt.Errorf("invalid %s annotation: trailing JSON data", AnnotationRootfsRwLayer)
	}
	if len(entries) == 0 {
		return nil, false, fmt.Errorf("%s annotation must not be empty", AnnotationRootfsRwLayer)
	}
	seen := map[string]struct{}{}
	for _, entry := range entries {
		if entry.Name == "" {
			return nil, false, fmt.Errorf("rootfs rw-layer entry name is required")
		}
		if _, exists := seen[entry.Name]; exists {
			return nil, false, fmt.Errorf("container %s configured more than once", entry.Name)
		}
		seen[entry.Name] = struct{}{}
		if err := validateEntry(spec, entry); err != nil {
			return nil, false, err
		}
	}
	return entries, true, nil
}

func validateEntry(spec *corev1.PodSpec, entry RootfsRwLayerEntry) error {
	if entry.VolumeName == "" {
		return fmt.Errorf("container %s volumeName is required", entry.Name)
	}
	if _, found := findContainer(spec, entry.Name); !found {
		return fmt.Errorf("container %s not found in pod spec", entry.Name)
	}
	if _, claimName, found := findPVCVolume(spec, entry.VolumeName); !found {
		return fmt.Errorf("volume %s must be a persistentVolumeClaim volume", entry.VolumeName)
	} else if claimName == "" {
		return fmt.Errorf("volume %s pvc claim name is empty", entry.VolumeName)
	}
	if err := validateRelativePath(entry.Path); err != nil {
		return fmt.Errorf("container %s path invalid: %w", entry.Name, err)
	}
	if len(entry.SpecialPath) > 0 && !entry.PersistentSpecialMounts {
		return fmt.Errorf("container %s specialPath requires persistentSpecialMounts", entry.Name)
	}
	paths := append([]string(nil), builtinSpecialPaths...)
	for _, path := range entry.SpecialPath {
		cleaned, err := validateSpecialPath(path)
		if err != nil {
			return fmt.Errorf("container %s specialPath %q invalid: %w", entry.Name, path, err)
		}
		for _, existing := range paths {
			if pathsOverlap(cleaned, existing) {
				return fmt.Errorf("container %s specialPath %q overlaps %q", entry.Name, path, existing)
			}
		}
		paths = append(paths, cleaned)
	}
	return nil
}

var builtinSpecialPaths = []string{
	"/var/lib/docker",
	"/var/lib/kubelet",
	"/var/lib/k0s",
	"/var/lib/rancher/k3s",
	"/var/lib/rancher/rke2",
	"/var/lib/buildkit",
	"/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs",
}

func validateSpecialPath(path string) (string, error) {
	if !filepath.IsAbs(path) {
		return "", fmt.Errorf("path must be absolute")
	}
	cleaned := filepath.Clean(path)
	if cleaned == string(filepath.Separator) {
		return "", fmt.Errorf("path must not be root")
	}
	return cleaned, nil
}

func pathsOverlap(left, right string) bool {
	return left == right || strings.HasPrefix(left, right+string(filepath.Separator)) || strings.HasPrefix(right, left+string(filepath.Separator))
}

func findContainer(spec *corev1.PodSpec, name string) (int, bool) {
	for index, container := range spec.Containers {
		if container.Name == name {
			return index, true
		}
	}
	return 0, false
}

func findPVCVolume(spec *corev1.PodSpec, volumeName string) (int, string, bool) {
	for index, volume := range spec.Volumes {
		if volume.Name == volumeName && volume.PersistentVolumeClaim != nil {
			return index, volume.PersistentVolumeClaim.ClaimName, true
		}
	}
	return 0, "", false
}

func validateRelativePath(path string) error {
	if path == "" {
		return nil
	}
	if filepath.IsAbs(path) {
		return fmt.Errorf("path must be relative")
	}
	cleaned := filepath.Clean(path)
	if cleaned == "." {
		return nil
	}
	if cleaned == ".." || len(cleaned) >= 3 && cleaned[:3] == "../" {
		return fmt.Errorf("path must not escape volume root")
	}
	return nil
}
