runtimeClass:
  name: sysbox-runc

nodeSelector: {}

image:
  repository: ghcr.io/w7panel/sysbox-deploy-k3s
  tag: latest

installer:
  podLabels: {}
  podAnnotations: {}

admission:
  enabled: false
  replicas: 1
  podLabels: {}
  podAnnotations: {}

snapshotter:
  enabled: false
